version: 2

jobs:
  build:
    docker:
      - image: cimg/openjdk:15.0.2

    working_directory: ~/repo

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml"}}
            - v1-dependencies

      - run: mvn dependency:go-offline
      - run: mvn package
      - run: mvn install

      - store_test_results:
          path: target/surefire-reports/

      - save-cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml"}}
      - run: mvn integration-test
