version: 2

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk

    working_directory: ~/repo

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml"}}
            - v1-dependencies

      - run: mvn dependency:go-offline
      - run: mvn package
      - run: mvn install
#          name: Save test results
#          command: |
#            mkdir -p ~/junit/
#            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
#          when: always

      - store_test_results:
          path: target/surefire-reports/

#      - store_artifacts:
#          path: ~/junit

      - save-cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml"}}
      - run: mvn integration-test
