version: 2

jobs:
  build:
    docker:
    - image: circleci/openjdk:11-jdk

    working_directory: ~/repo

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps: 
    - checkout
    -
    - store_test_results:
          path: test-results

    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "pom.xml"}}
        - v1-dependencies
    - run: mvn install

    - run: mvn dependency:go-offline

    - save-cache:
          paths:
          - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml"}}
    - run: mvn integration-test
